### ISSUE TITLE
Look into how projects specify author and maintainer details

### ISSUE THREAD

**Issue by brettcannon** [uranusjr/packaging-metadata-comparisons#8]
I.e. name and email addresses.

**Comment by uranusjr** [comment]
(This should probably be part of the document, but I don’t have time to modify it right now.)

Setuptools, Flit, and Poetry’s author/maintainer email fields translate directly to core metadata’s `Author-email` and `Maintainer-email`. They only accept one string, but the string (quote) *can contain a name and e-mail address in the legal forms for a RFC-822 From: header*, and therefore can contain multiple authors/maintainers, separated by comma.

Confusingly this also means that the email fields can contain author/maintainer names. Core metadata spec seems to suggest *Author* and *Maintainer* should contain more detailed contact information, but I don’t think I ever saw anyone do that in practice. So maybe we should try something different instead, say a list of mappings

```toml
[[metadata.author]]
name = "Tzu-ping Chung"
email = "uranusjr@gmail.com"
detail = "PyPA"  # Optional.

[[metadata.author]]
name = "Another author"
email = "another@company.com"
```

which automatically renders to the following core metadata

```
Author: Tzu-ping Chung, PyPA
       Another author
Author-email: Tzu-ping Chung <uranusjr@gmail.com>, Another author <another@company.com>
```

The same applies for the maintainer fields.

---

Edit: [Core metadata specification](https://packaging.python.org/specifications/core-metadata/)
